### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by EESports7** [TobyAdd/FishBot#1]
i would like to know

**Comment by Skyue1** [comment]
https://preshing.com/20170511/how-to-build-a-cmake-based-project/ read this

**Comment by TobyAdd** [comment]
https://github.com/TobyAdd/FishBot/assets/66429886/12a6a59e-faa3-49f7-9152-f2284bf6bced

P.S. - you need to install Visual Studio (With C++ Development Pack) and Visual Studio Code
